//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vFCS 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2003.02.06 at 03:42:14 PST 
//


package test.jaxb;


/**
 * Java content class for bookType complex type.
 *  <p>The following schema fragment specifies the expected content contained within this java content object.
 * <p>
 * <pre>
 * &lt;complexType name="bookType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ISBN" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="authors">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="authorName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="promotion">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="Discount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="None" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="publicationDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="bookCategory">
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *             &lt;enumeration value="magazine"/>
 *             &lt;enumeration value="novel"/>
 *             &lt;enumeration value="fiction"/>
 *             &lt;enumeration value="other"/>
 *           &lt;/restriction>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="itemId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface BookType {


    java.lang.String getItemId();

    void setItemId(java.lang.String value);

    java.lang.String getDescription();

    void setDescription(java.lang.String value);

    java.lang.String getName();

    void setName(java.lang.String value);

    java.util.Calendar getPublicationDate();

    void setPublicationDate(java.util.Calendar value);

    java.lang.String getPrice();

    void setPrice(java.lang.String value);

    test.jaxb.BookType.AuthorsType getAuthors();

    void setAuthors(test.jaxb.BookType.AuthorsType value);

    java.lang.String getBookCategory();

    void setBookCategory(java.lang.String value);

    long getISBN();

    void setISBN(long value);

    test.jaxb.BookType.PromotionType getPromotion();

    void setPromotion(test.jaxb.BookType.PromotionType value);


    /**
     * Java content class for annonymous complex type.
     *  <p>The following schema fragment specifies the expected content contained within this java content object.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="authorName" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface AuthorsType {


        java.util.List getAuthorName();

    }


    /**
     * Java content class for annonymous complex type.
     *  <p>The following schema fragment specifies the expected content contained within this java content object.
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="Discount" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="None" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface PromotionType {


        java.lang.String getNone();

        void setNone(java.lang.String value);

        java.lang.String getDiscount();

        void setDiscount(java.lang.String value);

    }

}
