//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.03 at 04:35:32 PM CET 
//


package org.knipsX.utils.JAXB.parser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}axes" minOccurs="0"/>
 *         &lt;element ref="{}pictureSets"/>
 *         &lt;element ref="{}exifFilterKeywords"/>
 *         &lt;element ref="{}wilcoxonTest" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "name",
    "description",
    "axes",
    "pictureSets",
    "exifFilterKeywords",
    "wilcoxonTest"
})
@XmlRootElement(name = "report")
public class Report {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String description;
    protected Axes axes;
    @XmlElement(required = true)
    protected PictureSets pictureSets;
    @XmlElement(required = true)
    protected ExifFilterKeywords exifFilterKeywords;
    protected WilcoxonTest wilcoxonTest;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the axes property.
     * 
     * @return
     *     possible object is
     *     {@link Axes }
     *     
     */
    public Axes getAxes() {
        return axes;
    }

    /**
     * Sets the value of the axes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Axes }
     *     
     */
    public void setAxes(Axes value) {
        this.axes = value;
    }

    /**
     * Gets the value of the pictureSets property.
     * 
     * @return
     *     possible object is
     *     {@link PictureSets }
     *     
     */
    public PictureSets getPictureSets() {
        return pictureSets;
    }

    /**
     * Sets the value of the pictureSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link PictureSets }
     *     
     */
    public void setPictureSets(PictureSets value) {
        this.pictureSets = value;
    }

    /**
     * Gets the value of the exifFilterKeywords property.
     * 
     * @return
     *     possible object is
     *     {@link ExifFilterKeywords }
     *     
     */
    public ExifFilterKeywords getExifFilterKeywords() {
        return exifFilterKeywords;
    }

    /**
     * Sets the value of the exifFilterKeywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExifFilterKeywords }
     *     
     */
    public void setExifFilterKeywords(ExifFilterKeywords value) {
        this.exifFilterKeywords = value;
    }

    /**
     * Gets the value of the wilcoxonTest property.
     * 
     * @return
     *     possible object is
     *     {@link WilcoxonTest }
     *     
     */
    public WilcoxonTest getWilcoxonTest() {
        return wilcoxonTest;
    }

    /**
     * Sets the value of the wilcoxonTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link WilcoxonTest }
     *     
     */
    public void setWilcoxonTest(WilcoxonTest value) {
        this.wilcoxonTest = value;
    }

}
